app/src/main/java/com/arygm/quickfix/ui/authentication/LoginScreen.kt
app/src/main/java/com/arygm/quickfix/ui/authentication/PasswordScreen.kt
app/src/main/java/com/arygm/quickfix/ui/authentication/RegistrationScreen.kt
app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt

Added :
- Welcome screen with programmable buttons (login, sign in, and google login)
- A login screen that a user that chooses not to log in with google will see
- A register screen that a user that chooses to register with our own account database will see
- A password setting screen 
All buttons in those screens are intentionally left functionless for the backend team to complete (@JitterKiller @ramshty @Autek)
commit by: Mehdi (@AnotherMedo) and Georges (@Sebbayra)

Add authentication UI

---

app/build.gradle.kts
gradle/libs.versions.toml

- Added Mockito core, inline, and Android libraries for unit testing.
- Added Mockk core, agent, and Android libraries for unit and UI testing.
- Updated `libs.versions.toml` with versions for Mockito and Mockk.
- Updated `build.gradle.kts` to include Mockito and Mockk dependencies for testing.

chore: add Mockito and Mockk libraries for unit and UI testing

---

.github/workflows/CI.yaml

- Changed the SonarCloud command in `.github/workflows/CI.yaml` from `./gradlew build sonar` to `./gradlew build check connectedCheck jacocoTestReport sonar`.
- This ensures that all checks and reports are generated before running the SonarCloud analysis.

ci: update SonarCloud command to include additional checks and reports

---

.github/workflows/android.yaml
app/build.gradle.kts

- Added `android.yaml` to configure GitHub Actions for building the APK.
- Included steps for signing and aligning the APK.
- Configured artifact upload for the release APK.

ci: add GitHub Actions workflow for building APK

---

app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
app/src/main/java/com/arygm/quickfix/model/profile/searchViewModel.kt
app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
app/src/test/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestoreTest.kt

- Implemented filtering functionality in `WorkerProfileRepositoryFirestore` to support querying worker profiles based on:
- `fieldOfWork`: filters by specified job field (e.g., Plumber, Electrician)
- `hourlyRateThreshold`: filters profiles with hourly rates below a specified threshold
- `location` and `radiusInKm`: filters profiles within a geographic radius based on latitude and longitude
- Designed robust unit tests for each filter criteria and combined criteria, covering success and failure scenarios
- Used mock Firestore queries to simulate chaining behavior and ensure accurate filtering across all conditions

feat: add worker profile filtering and unit tests

---

app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt

Fixed a Navigation Typo Regarding Google Sign In, where we would always enter the info screen instead of just the first time.

fix: Fix Navigation Typo Regarding Google Sign In

---

app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt

Since I couldn't manually test because of emulator network error, i just checked really quick on another member's laptop so i missed this slight issue, won't be repeated.
The issue was we were entering google info every time except the creation which should be the exact opposite.

fix: Fix the navigation where we inversed the logic

---

app/build.gradle.kts

This pull request adds Windows compatibility for the `connectedCheckWithEmulators` task in the Gradle script.
- Updated the Gradle script to handle Windows-specific paths and commands.
- Ensured that emulator startup and shutdown commands work on Windows.
- Added conditional checks for OS type to apply appropriate configurations.
- Verified that the `connectedCheckWithEmulators` task runs successfully on Windows.
- Ensured that emulators start up and shut down correctly on Windows.
- This change improves the cross-platform compatibility of the build process, allowing developers on Windows to run the `connectedCheckWithEmulators` task seamlessly.

ci: Add Windows compatibility for connectedCheckWithEmulators task

---

app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementScreenTest.kt
app/src/main/java/com/arygm/quickfix/MainActivity.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixTextFieldCustom.kt
app/src/main/java/com/arygm/quickfix/ui/search/Announcement.kt
app/src/main/res/drawable/calendar.xml
app/src/main/res/drawable/upload_image.xml

This pull request implements the Announcement screen according to the Figma design. It includes the layout, structure, and necessary fields such as title, category, description, and location. The screen also includes buttons for availability and uploading pictures, though the functionality for these buttons is yet to be implemented.
Related to #123 
Next steps will involve building the composables for managing availability and uploading pictures, which are essential features for completing the Announcement screen functionality.
The PR also includes tests to ensure the proper behavior of the screen components.

Build Announcement Screen Based on Figma Design

---

app/src/androidTest/java/com/arygm/quickfix/kaspresso/MainActivityTest.kt

Strange for this fix since all the tests were ran before merging #136, but surprisingly an import was missing despite the fact that the CI passed before merging.

Import missing in end2end Test

---

app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuiickFixServicesChoosing.kt

feat: Implement ChooseServiceTypeSheet and UI tests for service selection modal
- Added `ChooseServiceTypeSheet` component in QuiickFixServicesChoosing.kt, providing a dynamic modal UI for selecting service types with customizable options.
- Created `ChooseServiceTypeSheetTest` in ChooseServiceTypeSheetTest.kt to validate UI interactions, including service selection, Apply, and Reset actions.
- Used relative dimensions in the `ChooseServiceTypeSheet` component for better responsiveness across screen sizes.
Related to issue #151

feat: Implement ChooseServiceTypeSheet and UI tests for service selection

---

app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
app/src/main/java/com/arygm/quickfix/model/profile/Profile.kt
app/src/main/java/com/arygm/quickfix/model/profile/WorkerProfileRepositoryFirestore.kt
app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
app/src/test/java/com/arygm/quickfix/model/search/WorkerFilterTest.kt

Added filterWorkersByAvailability function to filter workers based on:
Working hours: Workers are excluded if the selected time is before their start time or after their end time, including minute-level precision.
Unavailability: Workers are excluded if they are unavailable on any of the selected days.
And integrated it in the SearchWorkerResult screen and it's actually the onOkClick function of the QuickFixAvailabilityBottomSheet.
Tested the filtering function in some UI tests as well as some unit tests.

Add Availability Worker Filtering in SearchWorkerResult screen

---

app/src/androidTest/java/com/arygm/quickfix/ui/profile/ProfileConfigurationScreenTest.kt
app/src/main/java/com/arygm/quickfix/ui/authentication/GoogleInfoScreen.kt
app/src/main/java/com/arygm/quickfix/ui/authentication/WelcomeScreen.kt
app/src/main/java/com/arygm/quickfix/ui/profile/AccountConfiguration.kt
app/src/main/java/com/arygm/quickfix/ui/profile/ProfileScreen.kt
app/src/main/java/com/arygm/quickfix/utils/Preferences.kt
app/src/test/java/com/arygm/quickfix/utils/PreferencesTest.kt

Second PR towards implementing a fully fledged _**offline mode**_. It is no secret that it currently is very cumbersome to use the `PreferencesViewModel` in its current state: Having to use a co-routine or a `LaunchedEffect` for every call and having to nest cache calls to load multiple values is very stinky... 
Thus, this PR brings a few nice changes to make it easier to call the cache.
_**Commit history**_:
`task: add helper functions and refactor utils`
`task: update screens to use helper functions`
`test: test new methods and ktfmt format`

[Offline Mode] - Implement helper functions to interface DataStore

---

app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixOfflineBarTest.kt
app/src/main/java/com/arygm/quickfix/MainActivity.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixOfflineBar.kt

One of the last remaining puzzle pieces to finally finish the _**Offline Mode**_. That is, an indicator warning the user that the app is not connected to the internet. 
_**Commit history:**_
`task: add offline bar element and implement it with main activity`
`test: add tests for offline bar and ktfmt format`

task: add offline bar element and implement it with main activity

---

app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsScreenTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixDetailsdescription.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixSlindingWindowWithContent.kt

This pull request introduces new UI tests for QuickFix components and implements the QuickFixDetailsScreen UI in the Android project. The most important changes include the addition of test cases for QuickFixDetailsScreen and QuickFixSlidingWindowContent, and the implementation of the QuickFixDetailsScreen UI.
* [`app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDetailsScreenTest.kt`](diffhunk://#diff-66c312f025fd400dcb0c1f961f688c432e219f590fd4824904864cea63b39833R1-R161): Added new test cases to verify the display of title, services, description (both collapsed and expanded), and images in the QuickFixDetailsScreen.
* [`app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixSlidingWindowContentTest.kt`](diffhunk://#diff-f90af2665e9dd1edaeafdb06c94e8958f4c62141a5db …

feat: Add tests and components for QuickFix Details and Sliding Window

---

app/src/androidTest/java/com/arygm/quickfix/ui/elements/ChooseServiceTypeSheetTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixAvailabilityBottomSheetTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixDateTimePickerTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheetTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/quickfix/QuickFixFirstStepTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/search/SearchWorkerResultScreenTest.kt
app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixLocationFilterBottomSheet.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixServicesChoosing.kt
app/src/main/java/com/arygm/quickfix/ui/search/ExpandableCategoryItem.kt
app/src/main/java/com/arygm/quickfix/ui/search/SearchWorkerResult.kt
app/src/main/java/com/arygm/quickfix/utils/String.kt
app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt
app/src/test/java/com/arygm/quickfix/utils/StringTest.kt

---
This pull request introduces changes to specific components, focusing on improving modularity, usability, and user experience. Below are the detailed changes made to the code:
---
- Refactored `SearchWorkerProfileResult`:
- Handled the distance to workers based on selected distance in the filter, default being current phone location.
- Made it so that now the filter row contains a tune button and a lazy row of filters, the tune button handles visibility.
- Handled bugs with the reapply filters.
- Made the highest rating filter clearable.
- Changed the filter button's colors based on if they are applied or not.
---
- Enhanced multi-service selection support:
- Added `selectedServices` as a parameter to initialize preselected values.
- Updated `onApplyClick` to handle multiple selected …

Refine Filter Interactions and SearchViewModel and Filter Composables

---

app/build.gradle.kts
app/src/androidTest/java/com/arygm/quickfix/ui/home/MessageUserNoModeScreenTest.kt
app/src/main/java/com/arygm/quickfix/model/messaging/Chat.kt
app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepository.kt
app/src/main/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestore.kt
app/src/main/java/com/arygm/quickfix/model/messaging/ChatViewModel.kt
app/src/main/java/com/arygm/quickfix/model/offline/large/Converters.kt
app/src/main/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabase.kt
app/src/main/java/com/arygm/quickfix/model/offline/large/messaging/ChatDao.kt
app/src/main/java/com/arygm/quickfix/model/offline/large/messaging/ChatEntity.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/noModeUI/authentication/WelcomeScreen.kt
app/src/test/java/com/arygm/quickfix/model/messaging/ChatRepositoryFirestoreTest.kt
app/src/test/java/com/arygm/quickfix/model/messaging/ChatViewModelTest.kt
app/src/test/java/com/arygm/quickfix/model/offline/large/ConvertersTest.kt
app/src/test/java/com/arygm/quickfix/model/offline/large/QuickFixRoomDatabaseTest.kt
app/src/test/java/com/arygm/quickfix/model/offline/large/messaging/ChatDaoTest.kt
app/src/test/java/com/arygm/quickfix/model/offline/large/messaging/ChatEntityTest.kt
build.gradle.kts
gradle/libs.versions.toml

Here is yet another _**Offline Mode**_ centered PR 😄. This time, for large _(large with respect to it size at least)_ data.
This PR aims at making the _**Offline Mode**_ more robust and more complete with full chat and message caching.
_**Feature Overview:**_
- Chat data caching
- Message serialization and storage¹
_**Commit history:**_
`task: update dependencies to use Room`²
`task: update chat logic to include room usage`
`test: test the chat caching and format`

[Offline Mode] - Implement chat caching using Room

---

app/src/androidTest/java/com/arygm/quickfix/ui/search/AnnouncementDetailTest.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/UserModeNavGraph.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/AnnouncementDetail.kt

This PR introduces a detailed view of an announcement, enabling users and workers to interact with posted announcements. The view supports:  
- **Users**: Update or delete their own announcements.  
- **Workers**: View the details of announcements proposed to them and propose a quickfix.
Additionally, this PR includes comprehensive **tests** to ensure the functionality of the new screen.
---
1. **Detailed View of an Announcement**  
- Displays the announcement's title, description, location, and availability slots.  
- Supports image previews with a counter (e.g., "1 of X").
2. **User-Specific Capabilities**  
- Users can **edit** the description and availability of their announcements.  
- Users can **delete** their announcements with a single action.
3. **Worker-Specific Capabilities** …

Add Detailed Announcement View

---

app/src/androidTest/java/com/arygm/quickfix/kaspresso/HomeUserNoModeScreenTest.kt
app/src/androidTest/java/com/arygm/quickfix/ui/elements/QuickFixToolboxFloatingButtonTest.kt
app/src/main/java/com/arygm/quickfix/ui/elements/QuickFixToolboxFloatingButton.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt

The first step into adding a brand new feature, a _**toolbox**_ that will allow the user to seamlessly navigate to a:
- Map utility to visualize the workers around
- AI ChatBot to aid in navigating the app
- Projects (Not sure to be implemented yet)
_**Commit History:**_
`task: implement floating toolbox button`
`test: add tests for floating button`
`task: include toolbox in homescreen`
`test: write tests for new functionality and ktfmt`

[Toolbox] - Add the toolbox floating button

---

app/src/androidTest/java/com/arygm/quickfix/ui/home/EarningsWidgetTest.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/workerMode/home/EarningsWidget.kt

This PR implements the **EarningsWidget** as part of the Worker HomeScreen in the QuickFix app. The **EarningsWidget** displays key earning statistics for the worker, including:
- Personal balance
- Earnings this month
- Average selling price
- Active orders with their total value
Additionally, this PR includes comprehensive **unit tests** to ensure correct rendering and behavior of the `EarningsWidget`.
---
1. **EarningsWidget Implementation**
- Displays detailed earning statistics:
- Personal balance
- Earnings this month
- Average selling price
- Active orders with their respective values
- Added `testTag`s to key components for easier UI testing.
2. **Unit Tests**
- Added tests to verify that the `EarningsWidget` renders correctly with sample data.
---
---
- Verified that the …

Implement EarningsWidget

---

app/src/main/java/com/arygm/quickfix/model/search/SearchViewModel.kt
app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/search/SearchOnBoarding.kt
app/src/test/java/com/arygm/quickfix/model/profile/SearchViewModelTest.kt

Instead of fetching all profiles on each value changes, we fetch them in the SearchOnBoarding initially and each time we change the search query we filter the initial list.

Search Engine Fix

---

app/src/main/java/com/arygm/quickfix/ui/uiMode/appContentUI/userModeUI/home/HomeScreen.kt

Literally the smallest PR I have ever made, there really isn't much to it other than removing the call to the Pen icon in the list of used icons for the toolbox

Remove the pen icon from the toolbox
